name: Train Model with MLflow

on:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/train.yml'

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12.7" # Pastikan versi ini sama dengan di conda.yaml
        
    - name: Run MLflow Project
      # Perintah ini secara otomatis akan menggunakan Conda untuk membuat 
      # environment dari 'conda.yaml' sebelum menjalankan skrip.
      run: mlflow run MLProject