name: Train Model with MLflow

on:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/train.yml'

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12.7" 
        
    # --- LANGKAH TAMBAHAN YANG KRUSIAL ---
    - name: Install MLflow in base environment
      run: pip install mlflow==2.19.0
        
    - name: Run MLflow Project
      # Sekarang perintah 'mlflow' sudah tersedia dan bisa digunakan
      run: mlflow run MLProject